pipeline {
    agent any

    environment {
        AWS_REGION = 'eu-west-2'
        ECR_REPOSITORY = '160071257600.dkr.ecr.eu-west-2.amazonaws.com'
        IMAGE_NAME = 'sample-ecr'
        IMAGE_TAG = 'latest'
    }

    stages {

        stage('Terraform Plan') {
            steps {
                echo 'Running Terraform Plan on $(pwd)/infra'
                sh '''
                cd infra
                terraform init
                '''
            }
        }

        stage('Terraform Plan') {
            steps {
                    withCredentials([file(credentialsId: 'aws_creds', variable: 'AWS_CREDENTIALS_FILE')]) {
                        script {
                            sh '''
                            mkdir -p ~/.aws
                            cp $AWS_CREDENTIALS_FILE ~/.aws/credentials
                            cd ./infra
                            terraform plan
                            '''
                        }
                    }
                }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}
