pipeline {
    agent any

    environment {
        AWS_REGION = 'eu-west-2'
        ECR_REPOSITORY = '160071257600.dkr.ecr.eu-west-2.amazonaws.com'
        IMAGE_NAME = 'sample-ecr'
        IMAGE_TAG = 'latest'
    }

    stages {
        stage('Login to AWS') {
            steps {
                withCredentials([file(credentialsId: 'aws_creds', variable: 'AWS_CREDENTIALS_FILE')]) {
                    script {
                        echo 'Setting up AWS credentials'
                        sh '''
                        mkdir -p ~/.aws
                        cp $AWS_CREDENTIALS_FILE  ~/.aws/credentials
                        '''
                    }
                }
                
            }
        }

        stage('Terraform init') {
            steps {
                echo 'Initializing terraform infrastructure'
                sh '''
                cd infra
                terraform init
                '''
            }
        }

        stage('Terraform Plan & validate') {
            steps {
                    echo " Validating terraform code"
                    sh '''
                    cd infra
                    terraform fmt
                    terraform validate
                    '''
                    echo "Running Terraform Plan"
                    sh '''
                    cd infra
                    terraform validate
                    terraform plan  -out=tf-plan
                    '''
                }
        }
        stage('Terraform Apply') {
            steps {
                    echo "Deploying terraform infrastructure"
                    sh '''
                    cd infra
                    terraform apply tf-plan
                    '''
                }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}
