pipeline {
    agent any

    environment {
        AWS_REGION = 'eu-west-2'
        ECR_REPOSITORY = '160071257600.dkr.ecr.eu-west-2.amazonaws.com'
        IMAGE_NAME = 'sample-ecr'
        IMAGE_TAG = 'latest'
    }

    stages {

        stage('Terraform Plan') {
            steps {
                echo 'Running Terraform Plan on $(pwd)/infra'
                sh '''
                cd 
                '''
            }
        }

        stage('Terraform apply') {
            steps {
                    withCredentials([file(credentialsId: 'aws_creds', variable: 'AWS_CREDENTIALS_FILE')]) {
                        script {
                            sh '''
                            mkdir -p ~/.aws
                            cp $AWS_CREDENTIALS_FILE ~/.aws/credentials

                            #Authenticate with ECR
                            aws ecr get-login-password --region ${AWS_REGION} > /kaniko/.docker/config.json
                            export IMAGE_URL=${ECR_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}
                
                            cd ./infra

                            '''
                        }
                    }
                }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}
