---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: 160071257600.dkr.ecr.eu-west-2.amazonaws.com/sample-ecr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_DATABASE_USER
              value: user
            - name: MYSQL_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_root_password
            - name: MYSQL_DATABASE_DB
              value: messages_db
            - name: MYSQL_DATABASE_HOST
              value: mysql
        - name: fluentd
          image: fluent/fluentd:latest
          env:
          - name: AWS_REGION
            value: "your-region"
          volumeMounts:
          - name: app-logs
            mountPath: /var/log/app 
          - name: fluentd-config
            mountPath: /fluentd/etc/fluent.conf
            subPath: fluent.conf

      volumes:
      - name: app-logs
        emptyDir: {} 
      - name: fluentd-config
        configMap:
          name: fluentd-config

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi
  type: LoadBalancer