apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mysql" 
