apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/app/*.log
      pos_file /var/log/fluentd-flask-app.pos
      time_format %Y-%m-%dT%H:%M:%S.%N%z
      tag flask.*
      format none
      read_from_head true
    </source>

    <match flask.*>
      @type cloudwatch_logs
      log_group_name eks-python-app-log-group
      log_stream_name fluentd-sidecar-logs
      auto_create_stream true
      region your-region
    </match>
