apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: default
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/app/app.log
      pos_file /var/log/app/app.log.pos
      tag flask.app  
      format none   
    </source>

    <match flask.app>
      @type cloudwatch_logs
      log_group_name eks-python-app-log-group
      log_stream_name fluentd-sidecar-logs
      auto_create_stream true
      region eu-west-2
    </match>