apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
---
apiVersion: iam.services.k8s.aws/v1alpha1
kind: IAMRole
metadata:
  name: api-service-iam-role
spec:
  roleName: apiServiceRole
  assumeRolePolicyDocument:
    Version: '2012-10-17'
    Statement:
      - Effect: Allow
        Principal:
          Service: ec2.amazonaws.com
        Action: sts:AssumeRole
  policyDocument:
    Version: '2012-10-17'
    Statement:
      - Effect: Allow
        Action: ecr:*
        Resource: "*"
