pipeline {
    agent any

    environment {
        AWS_REGION = 'eu-west-2'
        ECR_REPOSITORY = '160071257600.dkr.ecr.eu-west-2.amazonaws.com'
        IMAGE_NAME = 'sample-ecr'
        IMAGE_TAG = 'latest'
    }

    stages {
        stage('Install Dependencies') {
            steps {

                echo 'Installing Python dependencies...'
                sh '''
                pwd
                cd ./app
                pip3 install --break-system-packages -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                echo 'Running tests...'
                // Example of running tests using pytest
                //sh 'pytest tests/'
            }
        }

        stage('Build Docker Image') {
            steps {
                    withCredentials([file(credentialsId: 'aws_creds', variable: 'AWS_CREDENTIALS_FILE')]) {
                        script {
                            sh '''
                            mkdir -p ~/.aws
                            cp $AWS_CREDENTIALS_FILE ~/.aws/credentials

                            #Authenticate with ECR
                            aws ecr get-login-password --region ${AWS_REGION} > /kaniko/.docker/config.json
                            export IMAGE_URL=${ECR_REPOSITORY}/${IMAGE_NAME}:${IMAGE_TAG}
                
                            cd ./app
                            /kaniko/executor \
                                --context `pwd` \
                                --dockerfile `pwd`/Dockerfile \
                                --destination ${IMAGE_URL} \
                                --platform linux/amd64
                            '''
                        }
                    }
                }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}
